### ISSUE TITLE
Issue in Call Processor createB2BUA

### ISSUE THREAD

**Issue by lylepratt** [davehorton/drachtio-rtpengine-webrtcproxy#9]
Greetings! I'm working on a personal project and trying to get my feet (more) wet with your awesome framework!

I'm getting a weird error when I try to make a call:

```
{"level":30,"time":1591977240517,"msg":"received invite from tcp/172.17.0.1:sip:15125551234@127.0.0.1:5060 with request uri sip:15125551234@127.0.0.1:5060","pid":51588,"hostname":"TX-LPRATT.austin.rr.com","v":1}
{"level":30,"time":1591977240522,"msg":"sending INVITE to B with {\"headers\":{\"CSeq\":\"1 INVITE\"},\"localSdpB\":\"v=0\\r\\no=- 7110424578102811745 2 IN IP4 172.17.0.3\\r\\ns=-\\r\\nt=0 0\\r\\na=msid-semantic: WMS 4R0K0XHWqbyIhSCNY0uKMWJBRjzSRJKxpJAG\\r\\nm=audio 23080 RTP/AVP 111 103 104 9 0 8 106 105 13 110 112 113 126\\r\\nc=IN IP4 172.17.0.3\\r\\na=msid:4R0K0XHWqbyIhSCNY0uKMWJBRjzSRJKxpJAG 40dedea3-341d-422e-b1c7-b951081eb8e5\\r\\na=rtcp-fb:111 transport-cc\\r\\na=ssrc:2700220992 cname:ESS9SId01lYlAiEa\\r\\na=ssrc:2700220992 msid:4R0K0XHWqbyIhSCNY0uKMWJBRjzSRJKxpJAG 40dedea3-341d-422e-b1c7-b951081eb8e5\\r\\na=ssrc:2700220992 mslabel:4R0K0XHWqbyIhSCNY0uKMWJBRjzSRJKxpJAG\\r\\na=ssrc:2700220992 label:40dedea3-341d-422e-b1c7-b951081eb8e5\\r\\na=mid:0\\r\\na=rtpmap:111 opus/48000/2\\r\\na=rtpmap:103 ISAC/16000\\r\\na=rtpmap:104 ISAC/32000\\r\\na=rtpmap:9 G722/8000\\r\\na=rtpmap:0 PCMU/8000\\r\\na=rtpmap:8 PCMA/8000\\r\\na=rtpmap:106 CN/32000\\r\\na=rtpmap:105 CN/16000\\r\\na=rtpmap:13 CN/8000\\r\\na=rtpmap:110 telephone-event/48000\\r\\na=rtpmap:112 telephone-event/32000\\r\\na=rtpmap:113 telephone-event/16000\\r\\na=rtpmap:126 telephone-event/8000\\r\\na=fmtp:111 minptime=10;useinbandfec=1\\r\\na=sendrecv\\r\\na=rtcp:23081\\r\\n\",\"proxyRequestHeaders\":[\"from\",\"to\",\"proxy-authorization\",\"authorization\",\"supported\",\"allow\",\"content-type\",\"user-agent\"],\"proxyResponseHeaders\":[\"proxy-authenticate\",\"www-authenticate\",\"accept\",\"allow\",\"allow-events\"]}","pid":51588,"hostname":"TX-LPRATT.austin.rr.com","v":1}
here
(node:51588) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'has' of undefined
    at /Users/lpratt/Documents/Ubuntu/satroute/node_modules/drachtio-srf/lib/srf.js:710:20
    at Array.forEach (<anonymous>)
    at copyUACHeadersToUAS (/Users/lpratt/Documents/Ubuntu/satroute/node_modules/drachtio-srf/lib/srf.js:708:28)
    at /Users/lpratt/Documents/Ubuntu/satroute/node_modules/drachtio-srf/lib/srf.js:786:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:51588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

I'm assuming I'm missing something obvious....

**Comment by lylepratt** [comment]
This was a silly issue on my part. I needed to dial a configured trunk domain in the "credentials" config.
